/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as AcceptAndDepositScriptJson } from "../AcceptAndDeposit.ral.json";
import { default as CancelEscrowScriptJson } from "../CancelEscrow.ral.json";
import { default as ClaimAfterDeadlineScriptJson } from "../ClaimAfterDeadline.ral.json";
import { default as DeliverScriptJson } from "../Deliver.ral.json";
import { default as OpenDisputeScriptJson } from "../OpenDispute.ral.json";
import { default as RefundByFreelancerScriptJson } from "../RefundByFreelancer.ral.json";
import { default as ReleasePaymentScriptJson } from "../ReleasePayment.ral.json";
import { default as ResolveDisputeScriptJson } from "../ResolveDispute.ral.json";
import { default as SubmitEvidenceScriptJson } from "../SubmitEvidence.ral.json";

export const AcceptAndDeposit = new ExecutableScript<{
  escrow: HexString;
  collateral: bigint;
}>(Script.fromJson(AcceptAndDepositScriptJson, "", []), getContractByCodeHash);

export const CancelEscrow = new ExecutableScript<{ escrow: HexString }>(
  Script.fromJson(CancelEscrowScriptJson, "", []),
  getContractByCodeHash
);

export const ClaimAfterDeadline = new ExecutableScript<{ escrow: HexString }>(
  Script.fromJson(ClaimAfterDeadlineScriptJson, "", []),
  getContractByCodeHash
);

export const Deliver = new ExecutableScript<{
  escrow: HexString;
  link: HexString;
}>(Script.fromJson(DeliverScriptJson, "", []), getContractByCodeHash);

export const OpenDispute = new ExecutableScript<{
  escrow: HexString;
  reason: HexString;
}>(Script.fromJson(OpenDisputeScriptJson, "", []), getContractByCodeHash);

export const RefundByFreelancer = new ExecutableScript<{ escrow: HexString }>(
  Script.fromJson(RefundByFreelancerScriptJson, "", []),
  getContractByCodeHash
);

export const ReleasePayment = new ExecutableScript<{ escrow: HexString }>(
  Script.fromJson(ReleasePaymentScriptJson, "", []),
  getContractByCodeHash
);

export const ResolveDispute = new ExecutableScript<{
  escrow: HexString;
  toFreelancer: boolean;
  justification: HexString;
}>(Script.fromJson(ResolveDisputeScriptJson, "", []), getContractByCodeHash);

export const SubmitEvidence = new ExecutableScript<{
  escrow: HexString;
  evidence: HexString;
}>(Script.fromJson(SubmitEvidenceScriptJson, "", []), getContractByCodeHash);
