/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as TrustRegistryContractJson } from "../TrustRegistry.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace TrustRegistryTypes {
  export type State = Omit<ContractState<any>, "fields">;
  export type ScoreUpdatedEvent = ContractEvent<{
    freelancer: Address;
    oldScore: bigint;
    newScore: bigint;
  }>;

  export interface CallMethodTable {
    getScore: {
      params: CallContractParams<{ freelancer: Address }>;
      result: CallContractResult<bigint>;
    };
    calculateCollateral: {
      params: CallContractParams<{
        baseCollateral: bigint;
        freelancer: Address;
      }>;
      result: CallContractResult<bigint>;
    };
    initScore: {
      params: CallContractParams<{ freelancer: Address }>;
      result: CallContractResult<null>;
    };
    increaseScore: {
      params: CallContractParams<{ freelancer: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    decreaseScore: {
      params: CallContractParams<{ freelancer: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getScore: {
      params: SignExecuteContractMethodParams<{ freelancer: Address }>;
      result: SignExecuteScriptTxResult;
    };
    calculateCollateral: {
      params: SignExecuteContractMethodParams<{
        baseCollateral: bigint;
        freelancer: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    initScore: {
      params: SignExecuteContractMethodParams<{ freelancer: Address }>;
      result: SignExecuteScriptTxResult;
    };
    increaseScore: {
      params: SignExecuteContractMethodParams<{
        freelancer: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    decreaseScore: {
      params: SignExecuteContractMethodParams<{
        freelancer: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];

  export type Maps = { scores?: Map<Address, bigint> };
}

class Factory extends ContractFactory<TrustRegistryInstance, {}> {
  encodeFields() {
    return encodeContractFields({}, this.contract.fieldsSig, []);
  }

  eventIndex = { ScoreUpdated: 0 };

  at(address: string): TrustRegistryInstance {
    return new TrustRegistryInstance(address);
  }

  tests = {
    getScore: async (
      params: Omit<
        TestContractParams<
          never,
          { freelancer: Address },
          TrustRegistryTypes.Maps
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<bigint, TrustRegistryTypes.Maps>> => {
      return testMethod(this, "getScore", params, getContractByCodeHash);
    },
    calculateCollateral: async (
      params: Omit<
        TestContractParams<
          never,
          { baseCollateral: bigint; freelancer: Address },
          TrustRegistryTypes.Maps
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<bigint, TrustRegistryTypes.Maps>> => {
      return testMethod(
        this,
        "calculateCollateral",
        params,
        getContractByCodeHash
      );
    },
    initScore: async (
      params: Omit<
        TestContractParams<
          never,
          { freelancer: Address },
          TrustRegistryTypes.Maps
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<null, TrustRegistryTypes.Maps>> => {
      return testMethod(this, "initScore", params, getContractByCodeHash);
    },
    increaseScore: async (
      params: Omit<
        TestContractParams<
          never,
          { freelancer: Address; amount: bigint },
          TrustRegistryTypes.Maps
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<null, TrustRegistryTypes.Maps>> => {
      return testMethod(this, "increaseScore", params, getContractByCodeHash);
    },
    decreaseScore: async (
      params: Omit<
        TestContractParams<
          never,
          { freelancer: Address; amount: bigint },
          TrustRegistryTypes.Maps
        >,
        "initialFields"
      >
    ): Promise<TestContractResult<null, TrustRegistryTypes.Maps>> => {
      return testMethod(this, "decreaseScore", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: {},
    asset?: Asset,
    address?: string,
    maps?: TrustRegistryTypes.Maps
  ) {
    return this.stateForTest_(initFields, asset, address, maps);
  }
}

// Use this object to test and deploy the contract
export const TrustRegistry = new Factory(
  Contract.fromJson(
    TrustRegistryContractJson,
    "=14-2+bb=2-2+28=2-1=1+2=221-1+5=51-1+c=38+7a7e0214696e73657274206174206d617020706174683a2000=442",
    "f099882f2b813e0ed6ae776b4ceb1fdcf7e26301da87eafece2d01b52ef64b99",
    []
  )
);
registerContract(TrustRegistry);

// Use this class to interact with the blockchain
export class TrustRegistryInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    scores: new RalphMap<Address, bigint>(
      TrustRegistry.contract,
      this.contractId,
      "scores"
    ),
  };

  async fetchState(): Promise<TrustRegistryTypes.State> {
    return fetchContractState(TrustRegistry, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeScoreUpdatedEvent(
    options: EventSubscribeOptions<TrustRegistryTypes.ScoreUpdatedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TrustRegistry.contract,
      this,
      options,
      "ScoreUpdated",
      fromCount
    );
  }

  view = {
    getScore: async (
      params: TrustRegistryTypes.CallMethodParams<"getScore">
    ): Promise<TrustRegistryTypes.CallMethodResult<"getScore">> => {
      return callMethod(
        TrustRegistry,
        this,
        "getScore",
        params,
        getContractByCodeHash
      );
    },
    calculateCollateral: async (
      params: TrustRegistryTypes.CallMethodParams<"calculateCollateral">
    ): Promise<TrustRegistryTypes.CallMethodResult<"calculateCollateral">> => {
      return callMethod(
        TrustRegistry,
        this,
        "calculateCollateral",
        params,
        getContractByCodeHash
      );
    },
    initScore: async (
      params: TrustRegistryTypes.CallMethodParams<"initScore">
    ): Promise<TrustRegistryTypes.CallMethodResult<"initScore">> => {
      return callMethod(
        TrustRegistry,
        this,
        "initScore",
        params,
        getContractByCodeHash
      );
    },
    increaseScore: async (
      params: TrustRegistryTypes.CallMethodParams<"increaseScore">
    ): Promise<TrustRegistryTypes.CallMethodResult<"increaseScore">> => {
      return callMethod(
        TrustRegistry,
        this,
        "increaseScore",
        params,
        getContractByCodeHash
      );
    },
    decreaseScore: async (
      params: TrustRegistryTypes.CallMethodParams<"decreaseScore">
    ): Promise<TrustRegistryTypes.CallMethodResult<"decreaseScore">> => {
      return callMethod(
        TrustRegistry,
        this,
        "decreaseScore",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getScore: async (
      params: TrustRegistryTypes.SignExecuteMethodParams<"getScore">
    ): Promise<TrustRegistryTypes.SignExecuteMethodResult<"getScore">> => {
      return signExecuteMethod(TrustRegistry, this, "getScore", params);
    },
    calculateCollateral: async (
      params: TrustRegistryTypes.SignExecuteMethodParams<"calculateCollateral">
    ): Promise<
      TrustRegistryTypes.SignExecuteMethodResult<"calculateCollateral">
    > => {
      return signExecuteMethod(
        TrustRegistry,
        this,
        "calculateCollateral",
        params
      );
    },
    initScore: async (
      params: TrustRegistryTypes.SignExecuteMethodParams<"initScore">
    ): Promise<TrustRegistryTypes.SignExecuteMethodResult<"initScore">> => {
      return signExecuteMethod(TrustRegistry, this, "initScore", params);
    },
    increaseScore: async (
      params: TrustRegistryTypes.SignExecuteMethodParams<"increaseScore">
    ): Promise<TrustRegistryTypes.SignExecuteMethodResult<"increaseScore">> => {
      return signExecuteMethod(TrustRegistry, this, "increaseScore", params);
    },
    decreaseScore: async (
      params: TrustRegistryTypes.SignExecuteMethodParams<"decreaseScore">
    ): Promise<TrustRegistryTypes.SignExecuteMethodResult<"decreaseScore">> => {
      return signExecuteMethod(TrustRegistry, this, "decreaseScore", params);
    },
  };

  async multicall<Calls extends TrustRegistryTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TrustRegistryTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends TrustRegistryTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<TrustRegistryTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | TrustRegistryTypes.MultiCallParams
      | TrustRegistryTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      TrustRegistry,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
